# docker-compose.yml

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - go_mod_cache:/go/pkg/mod
      - ./uploads:/app/uploads
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL_MODE: disable
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    depends_on:
      - db
    networks:
      - app-network

  api_embeddings:
    build:
      context: ./api_embeddings
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - go_mod_cache:/go/pkg/mod
      - ./uploads:/app/uploads
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_EMBEDDINGS}
      POSTGRES_SSL_MODE: disable
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    depends_on:
      - db
    networks:
      - app-network

  telegram-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_BASE_URL: ${API_BASE_URL}
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  go_mod_cache:
  db_data:
